flask_test/__init__.py
import os
from flask import Flask
from flask import render_template
from flask_test import db, api
from flask_test.views import single, listview, report

def create_app(test_config=None):
    """
    Create and configure the app.

    Application factory. Any configuration, registration, and other setup the application needs
    will happen inside the function, then the application will be returned.
    """
    # configuration files are relative to the instance folder
    app = Flask(__name__, instance_relative_config=True)

    app.config.from_mapping(
        # Dummy value. Provide a random secret key in config.py
        SECRET_KEY='dev',
        # the path where the SQLite database file will be saved
        DATABASE=os.path.join(app.instance_path, 'flask-test.db'),
    )

    if test_config is None:
        # load the instance config, if it exists, when not testing
        app.config.from_pyfile('config.py', silent=True)
    else:
        # load the test config if passed in
        app.config.from_mapping(test_config)

    # ensure the instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    db.init_app(app)
    app.register_blueprint(api.bp)
    app.register_blueprint(listview.bp)
    app.register_blueprint(single.bp)
    app.register_blueprint(report.bp)

    @app.route('/')
    def hello_world():
        return render_template('index.html')

    return app

flask_test/views/listview.py
from flask import (Blueprint, Response, request, render_template)
import json
from flask_test import db
from flask_test.schema import FORM_SCHEMA
from flask_test.utils import row_as_json, list_as_json

bp = Blueprint('list', __name__)

@bp.route('/resource/<doc_type>', methods=['GET'])
def get(doc_type):
    data = db.get_list(doc_type)

    if 'application/json' in request.headers.get('accept'):
        response = json.dumps(list_as_json(data))
        return Response(response, mimetype="application/json")

    return render_template(
        'list.html',
        items=data,
        doc_type=doc_type,
        fields=FORM_SCHEMA[doc_type],
        get_options=db.get_list
    )

flask_test/views/report.py
import json
from flask import (Blueprint, Response, request, render_template)
from flask_test import db
from flask_test.utils import list_as_json

bp = Blueprint('report', __name__)

@bp.route('/Report', methods=['GET'])
def get():
    data = db.get_list("Report")

    if 'application/json' in request.headers.get('accept'):
        response = json.dumps(list_as_json(data))
        return Response(response, mimetype="application/json")

    return render_template(
        'report.html',
        items=data,
        doc_type="Report"
    )

flask_test/views/single.py
import json
from flask import (Blueprint, request, render_template)
from flask_test.db import Document
from flask_test.utils import row_as_json

bp = Blueprint('single', __name__)

@bp.route('/resource/<doc_type>/<doc_id>', methods=['GET'])
def get(doc_type, doc_id):
    doc = Document(doc_type, doc_id)
    data = doc.get()

    if 'application/json' in request.headers.get('accept'):
        return json.dumps(row_as_json(data))

    return render_template('single.html', doc=data, doc_type=doc_type)

flask_test/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a href="/"><span class="navbar-brand">Flask-Test</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('list.get', doc_type='Warehouse') }}">Warehouses</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('list.get', doc_type='Product') }}">Products</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('list.get', doc_type='ProductMovement') }}">ProductMovements</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('report.get') }}">Report</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container py-5">
        <section class="content">
            <header>
                {% block header %}{% endblock %}
            </header>
            {% block content %}{% endblock %}
        </section>
    </div>
</body>
</html>

flask_test/templates/index.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Home{% endblock %}</h1>
{% endblock %}

{% block content %}
<p>My try at Frappe's <a href="https://frappe.io/flask-test" target="_blank">Flask-Test</a>.</p>
<p>The source code can be found <a href="https://github.com/barredterra/flask-test" target="_blank">on GitHub</a>.</p>
{% endblock %}

flask_test/templates/list.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}{{ doc_type }}{% endblock %}</h1>
{% endblock %}

{% block content %}
    <form action="{{ url_for('api.create_doc', doc_type=doc_type) }}" method="post" class="form-inline" id="newdoc">
        {% for field in fields %}
            {% if field.get('type') == 'select' and field.get('options')%}
                <select class="form-control custom-select my-1 mr-sm-2" name="{{ field.get('name') }}">
                    <option value="" disabled selected>{{ field.get('display') }}</option>
                    {% for option in get_options(field.get('options')) %}
                        <option value="{{ option['id'] }}">{{ option['title'] }}</option>
                    {% endfor %}
                </select>
            {% else %}
                <label for="{{ field.get('name') }}-field" class="sr-only">{{ field.get('display') }}</label>
                <input 
                    type="{{ field.get('type') }}"
                    name="{{ field.get('name') }}"
                    id="{{ field.get('name') }}-field"
                    placeholder="{{ field.get('display') }}"
                    class="form-control my-1 mr-sm-2"
                >
            {% endif %}
        {% endfor %}
        <button type="submit" class="btn btn-primary my-1">Create</button>
    </form>
    <p>
        {% if items %}
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        {% for key in items[0].keys() if key != "id" %}
                            <th>{{ " ".join(key.split("_")) | title }}</th>
                        {% endfor %}
                    </tr>
                </thead>
                <tbody>
                    {% for i in items %}
                        <tr>
                            {% for key in i.keys() if key != "id" %}
                                <td>
                                    <a href="{{ url_for('single.get', doc_type=doc_type, doc_id=i['id']) }}">
                                        {{ i[key] }}
                                    </a>
                                </td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% endif %}
    </p>
{% endblock %}

flask_test/templates/report.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Report{% endblock %}</h1>
{% endblock %}

{% block content %}
{% if items %}
    <p>
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        {% for key in items[0].keys()%}
                            <th>{{ key | title }}</th>
                        {% endfor %}
                    </tr>
                </thead>
                <tbody>
                    {% for i in items %}
                    <tr>
                        {% for key in i.keys() %}
                            <td>{{ i[key] }}</td>
                        {% endfor %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </p>
{% else %}
<div class="text-center">
    <p>Move a <strong>Product</strong> into a <strong>Warehouse</strong> to see it's current stock.</p>
    <a href="{{ url_for('list.get', doc_type='ProductMovement') }}">
        <button class="btn btn-primary">New ProductMovement</button>
    </a>
</div>
{% endif %}
{% endblock %}

flask_test/templates/single.html
{% extends 'base.html' %}

{% block header %}
  <h1>
    {% block title %}{{ doc_type }}{% endblock %}
    <a href="{{ url_for('api.delete_doc', doc_type=doc_type, doc_id=doc['id']) }}" class="btn btn-secondary float-right my-1">Delete</a>
  </h1>
{% endblock %}

{% block content %}
  {% for key in doc.keys() %}
      <p><b>{{ " ".join(key.split("_")) | title }}</b>: {{ doc[key] }}</p>
  {% endfor %}
{% endblock %}